title: Practical Bitcoin Consultant
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "https://bitcoinsofia.com/"
site-twitter: https://twitter.com/BitcoinSofia/

# Author Settings
author: Bitcoin Sofia

logo-img: logo.jpg

about-author: "My name is Aleksandar Dinkov. I am a Software Engineer and I specialize in Bitcoin. <br/><br/> I can help you achieve better results by using Bitcoin as money and as a data ladger. <br/> <br/> I can also help you avoid investing resources in some of the less usefull blockchain ideas."

author-img: me.jpg


social-twitter: BitcoinSofia
social-github: Siko91 
social-linkedin: alexander-dinkov-26951ba8
social-email: aleks@bitcoinsofia.com

projects:
  - title: "Pipe Cash"
    href: https://pipecash.org/
    fa_icon: cogs
  - title: "BitSent LINK"
    href: https://bitsent.net/link.html
    fa_icon: external-link-square
  - title: "BitBtn"
    href: https://bitsent.net/link.html
    fa_icon: mouse-pointer

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
