title: Bitcoin Sofia
description: >
  Practical Bitcoin Consulting.
  Helping your business get an edge.
  Focused on practicality, not on trends.

permalink: ':title/'
baseurl: ""
url: "https://bitcoinsofia.com/"
site-twitter: https://twitter.com/BitcoinSofia/

# Author Settings
title2: Practical Bitcoin Consulting

author: Aleksandar Dinkov

logo-img: logo.jpg

about-author: "Aleksandar Dinkov.
  <hr/>
  <strong>Practical Bitcoin Consulting.</strong>
  <br/>Helping your business get an edge.
  <br/>Focused on practicality, not on trends.
  <br/>Do more with less."

author-img: me.jpg

social-twitter: BitcoinSofia
social-github: Siko91 
social-linkedin: alexander-dinkov-26951ba8
social-email: aleks@bitcoinsofia.com


menu:
  - title: Home
    fa_icon: home
    href: /
  - title: Blog
    fa_icon: pencil-square-o
    href: /blog/
  - title: Contact
    fa_icon: user
    href: /contact/

projects:
  - title: "Pipe Cash"
    href: https://pipecash.org/
    fa_icon: cogs
  - title: "BitSent LINK"
    href: https://bitsent.net/link.html
    fa_icon: user-secret
  - title: "BitBtn"
    href: https://bitsent.net/bitbtn.html
    fa_icon: toggle-off

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins dir:
  - jekyll-sitemap
  - jekyll-paginate

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
paginate_path: /blog/page:num/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
