title: Bitcoin Sofia
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "https://bitcoinsofia.com/"
site-twitter: https://twitter.com/BitcoinSofia/

# Author Settings
title2: Practical Bitcoin Consulting

author: Aleksandar Dinkov

logo-img: logo.jpg

about-author: "My name is Aleksandar Dinkov.
I am a Software Engineer and I specialize in Bitcoin."

author-img: me.jpg

social-twitter: BitcoinSofia
social-github: Siko91 
social-linkedin: alexander-dinkov-26951ba8
social-email: aleks@bitcoinsofia.com


menu:
  - title: Home
    fa_icon: home
    href: /
  - title: Blog
    fa_icon: pencil-square-o
    href: /blog/
  - title: Contact
    fa_icon: user
    href: /contact/

projects:
  - title: "Pipe Cash"
    href: https://pipecash.org/
    fa_icon: cogs
  - title: "BitSent LINK"
    href: https://bitsent.net/link.html
    fa_icon: user-secret
  - title: "BitBtn"
    href: https://bitsent.net/bitbtn.html
    fa_icon: toggle-off

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins dir:
  - jekyll-sitemap
  - jekyll-paginate

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
paginate_path: /blog/page:num/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
